version: 1.3.0

services:
  - memcached
  - php:
      version: 7.2

events:
  build:
    steps:
      - script1:
          script:
            - php -m
            - php -i
            - sudo /etc/init.d/memcached status
            - memcstat --servers=localhost
