version: 1.2.0
services:
  - mysql

events:
  build:
    steps:
      - hello:
          type: script
          script:
            - echo "test commit!"
            - echo "test commit!!!!!"
            - mysql -u root -proot -e 'CREATE DATABASE drupal;'
