// Define the feature level and scenario level properties here
module.exports = {
  // feature scope
  'pipelines-unauthenticated-url': '/auth/tokens',
  'mock-header': '/mock/header',
  'jobs-yml-file-name': 'jobs.yml',
  'jobs-list': '.el-card__title',
  'login': '#edit-submit-user-login',
  'sign-in': 'button.mat-primary',
  'no-jobs-yml-file-name': 'no-jobs.yml',
  'save': 'button.mat-primary',
  'header-value': 'input[name="headerValue"]',
  'app-id': '58bb63dd-57db-4d50-9a49-6b60d5921d14',
  'app-input': '[name="AppId"]',
  'activity-tab': '[tabtitle="Activity"]',
  'more-links': '#more-links-menu',
  'view-application-info': '//a[contains(text(),"View Application Info")]',
  'application-information': '//h1[text()="Application Information"]',
  'configure': '.configure-link',
  'start-a-job': '#start-job-no-jobs',
  'how-to-start-job-dialog': '.mat-dialog-container h4',
  'header-message': 'How to start a job',
  'branch-name': 'Test121 Branch',
  'branch-input': 'input[name="Branch"]',
  'branch-suggestion': '[item="Test121 Branch"]',
  'start': '#btn-start',
  'flash-message': '#flash-message',
  'success-message': 'Your job has started.',
};
