config.orm_options:
  group_retention:
    Buildsteps: 3 days
    Canary: 1 day
  system_log_retention: 3 days
  orm.proxies_dir: src/Acquia/WipIntegrations/DoctrineORM/Proxies
  orm.proxies_namespace: Acquia\WipIntegrations\DoctrineORM\Proxies
  orm.auto_generate_proxies: 0
  orm.em.options:
    mappings:
      -
        type: annotation
        namespace: Acquia\WipIntegrations\DoctrineORM\Entities
        path: src/Acquia/WipIntegrations/DoctrineORM/Entities
